### ISSUE TITLE
item.lua:22: attempt to index local 'img1' (a nil value)

### ISSUE THREAD

**Issue by Festus1965** [Rotfuchs-von-Vulpes/what_is_this_owo-minetest#2]
isso pode ser um problema dentro do minetest:builtin ... mas não tenho certeza

run on

test server engine 5.5.0 + MTG 5.5.0 - OK
test server engine 5.6.0-dev + MTG 5.6.0-dev OK

run on real server 5.5.0 + MTG 5.5.0
AsiaThailand

together with mod techage

get this
2022-05-08 07:55:57: ERROR[Main]: 
ServerError: AsyncErr: Lua: Runtime error from mod 'techage' in callback node_on_punch(): /home/thomas/minetest/bin/../builtin/game/item.lua:22: attempt to index local 'img1' (a nil value)
stack traceback:
/home/thomas/minetest/bin/../builtin/game/item.lua:22: in function 'inventorycube'
/home/thomas/minetest/bin/../mods/what_is_this_owo/help.lua:183: in function 'get_node_tile'
/home/thomas/minetest/bin/../mods/what_is_this_owo/init.lua:71: in function 'func'
...mas/minetest/bin/../builtin/profiler/instrumentation.lua:107: in function 'callback'
/home/thomas/minetest/bin/../builtin/game/item.lua:554: in function </home/thomas/minetest/bin/../builtin/game/item.lua:547>

server crash
mod now false

execute e teste ambas as versões em 5.5.0 e 4.5.0-dev

hoje de manhã começo a usá-lo no meu servidor 'AsiaThailand',
e durante quero abrir um techage:ta4_autocrafter
esta mensagem vem com falha.
Verifique, por favor.

**Comment by Rotfuchs-von-Vulpes** [comment]
I will try to reproduce the error right now.

**Comment by Rotfuchs-von-Vulpes** [comment]
![image](https://user-images.githubusercontent.com/61910532/167304252-4283574a-b675-4fc4-ae62-aac5fc6033a5.png)
I solved some incompatibilities that appeared with modpack, but they were just graphical issues, I couldn't reproduce your error.

**Comment by Festus1965** [comment]
I download this new commit,
set it active on my server AsiaThailand
and wait for restart to test ... will report then

**Comment by Festus1965** [comment]
you mod is since 4 hours running,
I click the same chest and nodes from techage as before
and no crash : techage was NOT updated

ok. SOLVED

The impact on my server AsiaThailand is 0%, so it works only when needed.
