### ISSUE TITLE
Crash indexing nil tiles

### ISSUE THREAD

**Issue by Ocraw** [Rotfuchs-von-Vulpes/what_is_this_owo-minetest#5]
https://github.com/Rotfuchs-von-Vulpes/what_is_this_owo-minetest/blob/dcc2e8bc6bff8bd5e228b83c4442639090997afa/help.lua#L182-L184

```lua
...
elseif tiles then 
 	if not tiles[1] then
...
```
Tested on mineclonia, sunflowers crash the game, changing that part as above fixes it for me, not sure if it causes issues with other blocks tho.

**Comment by Rotfuchs-von-Vulpes** [comment]
fix!
